#!/usr/bin/perl
#
# mth 2003 06 02
#
# cd to the Jmol directory and run me in order to resolve
# cvs conflicts in the headers of .java files after a merge
#
# the "conflict" files generated by CVS are saved as .java.bak
#
# this will probably only work on a Linux/Unix system
#

use strict;

open(CONFLICT, 'find src -name \*.java | xargs grep -l "<<<<<" |');
while (<CONFLICT>) {a
    chop;
    fixConflict($_);
}

sub fixConflict {
    my $filename = $_;
    my $filenameBak = $filename . ".bak";
    rename $filename, $filenameBak;
    open(IN, "<$filenameBak");
    open(OUT, ">$filename");
    my $state = 'lookingForConflict';
    while (<IN>) {
	my $line = $_;
	if ($state eq 'lookingForConflict') {
	    if ($line =~ /^<<<<</) {
		$state = 'discardingBeforeDoubleBar';
		next;
	    }
	    if ($line =~ /\s*(public|private|class)/) {
		$state = 'copyingFile';
	    }
	    print OUT $line;
	    next;
	}
	if ($state eq 'discardingBeforeDoubleBar') {
	    if ($line =~ /^=====/) {
		$state = 'copyingAfterDoubleBar';
	    }
	    next;
	}
	if ($state eq 'copyingAfterDoubleBar') {
	    if ($line =~ /^>>>>>/) {
		$state = 'lookingForConflict';
	    } else {
		print OUT $line;
	    }
	    next;
	}
	print OUT $line;
    }
    close IN;
    close OUT;
}
