#!/bin/sh

# Collect -D options as java arguments
command=java
while [ `echo $1 | egrep '^-D' | wc -l` != 0 ]; do
	command="$command $1"
	shift
done

if [ -f ./Jmol.jar ] ; then
  jarpath=./Jmol.jar
elif [ -f $JMOL_HOME/Jmol.jar ] ; then
  jarpath=$JMOL_HOME/Jmol.jar
elif [ -f /usr/share/jmol/Jmol.jar ] ; then
  jarpath=/usr/share/jmol/Jmol.jar
else
  echo Jmol.jar not found
  exit
fi
$command -jar $jarpath $@
