# Edited for Debian GNU/Linux.
DESTDIR =
BIN     = $(DESTDIR)/usr/X11R6/bin
LIBS    = ${DESTDIR}/usr/share/java

.SUFFIXES: $(SUFFIXES) .jar .java .class
           JMOL_HOME=$(PWD)
           JAVA_HOME= /usr/lib/j2sdk1.3
               JAVAC= $(JAVA_HOME)/bin/javac
                JAVA= $(JAVA_HOME)/bin/java
		JIKES= /usr/bin/jikes
             JAVADOC= $(JAVA_HOME)/bin/javadoc -private
        THREADS_FLAG=native
           CLASSPATH=${JMOL_HOME}/src/:${JAVA_HOME}/jre/lib/rt.jar:${LIBS}/sax.jar:${JMOL_HOME}/jars/aelfred.jar:${JMOL_HOME}/jars/cml.jar:${JMOL_HOME}/jars/Acme.jar:${JMOL_HOME}/jars/vecmath1.1-1.12.jar:${JMOL_HOME}/jars/junit.jar:${JMOL_HOME}/jars/jas.jar

#
# put Jmol.java first, so that compilation is fast
#

SOURCES = src/org/openscience/jmol/Jmol.java \
		src/org/openscience/jmol/ADFReader.java \
		src/org/openscience/jmol/AboutDialog.java \
		src/org/openscience/jmol/Aces2Reader.java \
		src/org/openscience/jmol/Angle.java \
		src/org/openscience/jmol/Animate.java \
		src/org/openscience/jmol/ArrowLine.java \
		src/org/openscience/jmol/AtomPropsMenu.java \
		src/org/openscience/jmol/AtomType.java \
		src/org/openscience/jmol/AtomTypeSet.java \
		src/org/openscience/jmol/AtomTypeTable.java \
		src/org/openscience/jmol/AtomTypesModel.java \
		src/org/openscience/jmol/BaseAtomType.java \
		src/org/openscience/jmol/Bond.java \
		src/org/openscience/jmol/CMLReader.java \
		src/org/openscience/jmol/CMLSaver.java \
		src/org/openscience/jmol/Charge.java \
		src/org/openscience/jmol/ChemFile.java \
		src/org/openscience/jmol/ChemFileReader.java \
		src/org/openscience/jmol/ChemFrame.java \
		src/org/openscience/jmol/ConsoleTextArea.java \
		src/org/openscience/jmol/DTDResolver.java \
		src/org/openscience/jmol/DecimalNumberField.java \
		src/org/openscience/jmol/Dihedral.java \
		src/org/openscience/jmol/DisplaySettings.java \
		src/org/openscience/jmol/Distance.java \
		src/org/openscience/jmol/FileSaver.java \
		src/org/openscience/jmol/FileTyper.java \
		src/org/openscience/jmol/FortranFormat.java \
		src/org/openscience/jmol/GamessReader.java \
		src/org/openscience/jmol/Gaussian92Reader.java \
		src/org/openscience/jmol/Gaussian94Reader.java \
		src/org/openscience/jmol/Gaussian98Reader.java \
		src/org/openscience/jmol/GaussianFile.java \
		src/org/openscience/jmol/HelpDialog.java \
		src/org/openscience/jmol/ImageTyper.java \
		src/org/openscience/jmol/JMolCDO.java \
		src/org/openscience/jmol/JmolException.java \
		src/org/openscience/jmol/JmolResourceHandler.java \
		src/org/openscience/jmol/JmolFileFilter.java \
		src/org/openscience/jmol/JpegEncoder.java \
		src/org/openscience/jmol/ListNode.java \
		src/org/openscience/jmol/LoopedStreams.java \
		src/org/openscience/jmol/Matrix3D.java \
		src/org/openscience/jmol/Measure.java \
		src/org/openscience/jmol/Measurement.java \
		src/org/openscience/jmol/MeasurementInterface.java \
		src/org/openscience/jmol/MeasurementList.java \
		src/org/openscience/jmol/MeasurementListEvent.java \
		src/org/openscience/jmol/MeasurementListListener.java \
		src/org/openscience/jmol/MultiLineHeaderRenderer.java \
		src/org/openscience/jmol/NMRShielding.java \
		src/org/openscience/jmol/PDBReader.java \
		src/org/openscience/jmol/PhysicalProperty.java \
		src/org/openscience/jmol/Preferences.java \
		src/org/openscience/jmol/ReaderFactory.java \
		src/org/openscience/jmol/Splash.java \
		src/org/openscience/jmol/StatusBar.java \
		src/org/openscience/jmol/TableMap.java \
		src/org/openscience/jmol/TableSorter.java \
		src/org/openscience/jmol/VProperty.java \
		src/org/openscience/jmol/Vibrate.java \
		src/org/openscience/jmol/Vibration.java \
		src/org/openscience/jmol/WhatsNewDialog.java \
		src/org/openscience/jmol/WholeNumberField.java \
		src/org/openscience/jmol/XYZReader.java \
		src/org/openscience/jmol/XYZSaver.java \
		src/org/openscience/jmol/displayPanel.java \
		src/org/openscience/jmol/poshTableSorter.java

CLASSES = $(SOURCES:%.java=%.class)

APPLET_SOURCES = src/org/openscience/miniJmol/JmolApplet.java \
		src/org/openscience/miniJmol/AtomTypeSet.java \
		src/org/openscience/miniJmol/BaseAtomType.java \
		src/org/openscience/miniJmol/CMLReader.java \
		src/org/openscience/miniJmol/CMLHandler.java \
		src/org/openscience/miniJmol/ChemFile.java \
		src/org/openscience/miniJmol/ChemFrame.java \
		src/org/openscience/miniJmol/DTDResolver.java \
		src/org/openscience/miniJmol/DisplaySettings.java \
		src/org/openscience/miniJmol/JMolCDO.java \
		src/org/openscience/miniJmol/JmolBeanTest.java \
		src/org/openscience/miniJmol/JmolSimpleBean.java \
		src/org/openscience/miniJmol/Matrix3D.java \
		src/org/openscience/miniJmol/PDBReader.java \
		src/org/openscience/miniJmol/XYZReader.java \
		src/org/openscience/miniJmol/displayPanel.java \
		src/org/openscience/miniJmol/Atom.java \
		src/org/openscience/miniJmol/BondRenderer.java \
		src/org/openscience/miniJmol/ChemFileReader.java \
		src/org/openscience/miniJmol/ReaderFactory.java \
		src/org/openscience/miniJmol/PDBReader.java \
		src/org/openscience/miniJmol/XYZReader.java \
		src/org/openscience/miniJmol/Gaussian98Reader.java

APPLET_CLASSES = $(APPLET_SOURCES:%.java=%.class)

APPLET_JMOL_SOURCES = src/org/openscience/jmol/FortranFormat.java \
		src/org/openscience/jmol/PhysicalProperty.java \
		src/org/openscience/jmol/ChemFileReader.java

APPLET_JMOL_CLASSES = $(APPLET_JMOL_SOURCES:%.java=%.class)

TEST_SOURCES = src/org/openscience/jmol/TestAll.java \
		src/org/openscience/jmol/TestAtomType.java \
		src/org/openscience/jmol/TestAtomTypeSet.java \
		src/org/openscience/jmol/TestAtomTypesModel.java \
		src/org/openscience/jmol/TestBaseAtomType.java \
		src/org/openscience/jmol/TestGaussian98Reader.java

TEST_CLASSES = $(TEST_SOURCES:%.java=%.class)

# 
# Some rulesets for compilation
#
# standard java files
#
%.class: %.java
	@echo "compiling $*"
	$(JIKES) -classpath $(CLASSPATH) -O -deprecation ../$<

all: archive

archive: $(CLASSES)
application: $(CLASSES)
applet: $(APPLET_CLASSES) $(APPLET_JMOL_CLASSES)
tests: $(TEST_CLASSES)

applet_archive: applet
	cd src/; jar cvf ../jars/JmolApplet.jar org/openscience/miniJmol/*.class $(APPLET_JMOL_CLASSES)

archive: application
	/bin/rm -f jars/jmol.jar
	cd src/; jar cvmf manifest ../jars/jmol.jar org/openscience/jmol/*.class  org/openscience/jmol/images/*.gif org/openscience/jmol/images/*.jpg org/openscience/jmol/Properties/Jmol.properties org/openscience/jmol/Data/AtomTypes org/openscience/jmol/Data/NMRReferences org/openscience/jmol/Data/cml.dtd org/openscience/jmol/Data/*.html
	chmod 664 jars/jmol.jar

# suggested by Christoph Steinbeck:
run: application
	$(JAVA) -classpath $(CLASSPATH) -Djmol.home=$(JMOL_HOME) org.openscience.jmol.Jmol

run_tests:
	$(JAVA) -classpath $(CLASSPATH) -Djmol.home=$(JMOL_HOME) org.openscience.jmol.TestAll

# suggested by Hugo Garcia:
doc:
	$(JAVADOC) -classpath $(CLASSPATH) -d doc -sourcepath . src/org.openscience.jmol org.openscience.miniJmol

clean:
	find . -name '*~' -exec $(RM) {} \;
	find src/org/openscience -name '*.class' -exec $(RM) {} \;
	# Messes with CVS:
	# /bin/rm -rf doc/*

install: application
	install -d ${BIN} ${LIBS}
	install ./jmol ${BIN}
	install ./jars/*jar ${LIBS}

