

newType('b','ON/OFF or TRUE/FALSE')
newType('i','integer')
newType('s','quoted string')
newType('f','decimal')
newType('color','(color name), [r,g,b],[xRRGGBB]')
newType('atm','ON/OFF or decimal(Angstroms) or integer(1/250 Angstroms)')
newType('xyz','a coordinate, in braces')
newType('v','variable -- see command')
newType('ix iy','integer pixel offsets')
newType('exp','an atom expression, in braces')







newVar('allowEmbeddedScripts','b')
newVar('allowRotateSelected','b')
newVar('ambient','_ambientPercent')
newVar('ambientpercent','i')
newVar('animationFps','i')
newVar('animFrameCallback','s')
newVar('appletProxy','s')
newVar('applySymmetryToBonds','b')
newVar('autobond','b')
newVar('axes','MOLECULAR,UNITCELL,WINDOW')
newVar('axesOrientationRasmol','reserved')
newVar('axesMode','i')
newVar('axesScale','f')
newVar('background','_backgroundColor')
newVar('backgroundColor','s')
newVar('backgroundModel','i')
newVar('bond','_showMultipleBonds')
newVar('bondmode','AND,OR')
newVar('bondModeOr','b')
newVar('bondRadiusMilliAngstroms','i')
newVar('bonds','_showMultipleBonds')
newVar('bondTolerance','f')
newVar('boundbox','atm')
newVar('cameraDepth','f')


newVar('cartoonRockets','b')



newVar('chainCaseSensitive','b')
newVar('charge','_formalCharge')
newVar('color','_defaultColorScheme')
newVar('colorRasmol','b')
newVar('colour','_defaultColorScheme')
newVar('dataSeparator','s')

newVar('debugScript','b')
newVar('defaultAngleLabel','s')
newVar('defaultcolors','_defaultColorScheme')
newVar('defaultColorScheme','JMOL,RASMOL')
newVar('defaultDirectory','s')
newVar('defaultDistanceLabel','s')
newVar('defaultLattice','i,xyz')
newVar('defaultLoadScript','s')
newVar('defaults','_defaultColorScheme')


newVar('defaultTorsionLabel','s')
newVar('defaultTranslucent','f')


newVar('diffuse','_diffusePercent')
newVar('diffusepercent','i')
newVar('dipoleScale','f')
newVar('disablePopupMenu','b')
newVar('display','_see {#.selectionHalos~selectionHalos ON/OFF}')
newVar('displayCellParameters','b')
newVar('dotsSelectedOnly','b')
newVar('dotSurface','b')
newVar('drawHover','b')
newVar('dynamicMeasurements','b')
newVar('echo','v')
newVar('fontsize','i')
newVar('forceAutoBond','b')
newVar('formalcharge','i')
newVar('frank','b')
newVar('greyscaleRendering','b')
newVar('hbond','_hbonds')
newVar('hbonds','BACKBONE,DOTTED,SIDECHAIN,SOLID')
newVar('hbondsBackbone','b')
newVar('hbondsSolid','b')
newVar('helpPath','s')
newVar('hermiteLevel','i')
newVar('hetero','_selectHetero')
newVar('hideNameInPopup','b')
newVar('hideNavigationPoint','b')
newVar('hideNotSelected','b')
newVar('highResolution','b')
newVar('history','i')
newVar('hoverCallback','s')
newVar('hoverDelay','f')
newVar('hoverLabel','s')
newVar('hydrogen','_selectHydrogen')
newVar('hydrogens','_selectHydrogen')
newVar('justifyMeasurements','b')
newVar('label','_labels')
newVar('labelAlignment','LEFT,RIGHT,CENTER')
newVar('labelAtom','b')
newVar('labelFront','b')
newVar('labelGroup','b')
newVar('labelOffset','ix iy')
newVar('labelPointer','b,BACKGROUND,NONE')
newVar('labels','s')
newVar('language','s')
newVar('loadStructCallback','s')
newVar('logLevel','i')
newVar('measure','_measurements')
newVar('measureAllModels','b')
newVar('measurement+B100','_measurements')
newVar('measurementLabels','b')
newVar('measurementNumbers','_measurementLabels')
newVar('measurements','b,ANGSTROMS, AU, BOHR, NM, NANOMETERS,PM, or PICOMETERS')
newVar('measures','_measurements')
newVar('messageCallback','s')
newVar('minBondDistance','f')
newVar('monitor','_measurements')
newVar('monitors','_measurements')
newVar('navigationDepth','f')
newVar('navigationMode','b')
newVar('navigationPeriodic','b')
newVar('navigationSlab','f')
newVar('navigationSpeed','f')
newVar('percentVdwAtom','i')
newVar('perspectiveDepth','b')
newVar('perspectiveModel','i')
newVar('pickCallback','s')
newVar('picking','s')
newVar('pickingSpinRate','i')
newVar('pickingStyle','s')
newVar('property','reserved')
newVar('propertyColorScheme','s')
newVar('radius','f')
newVar('rangeSelected','b')
newVar('refreshing','b')
newVar('ribbonAspectRatio','i')
newVar('ribbonBorder','b')
newVar('rotationRadius','f')
newVar('scale3d','_scaleAngstromsPerInch')
newVar('scaleAngstromsPerInch','f')
newVar('scriptQueue','b')
newVar('scriptReportingLevel','i')
newVar('selectionhalo','_selectionHalosEnabled')
newVar('selectionHalos','b')
newVar('selectHetero','b')
newVar('selectHydrogen','b')
newVar('sheetSmoothing','f')
newVar('showAxes','b')
newVar('showBoundBox','b')
newVar('showHiddenSelectionHalos','b')
newVar('showHydrogens','b')
newVar('showMeasurements','b')
newVar('showMultipleBonds','b')
newVar('showNavigationPointAlways','b')
newVar('showScript','i')
newVar('showSelections','b')
newVar('showUnitcell','b')
newVar('slabEnabled','b')
newVar('solvent','b')
newVar('solventProbe','b')
newVar('solventProbeRadius','f')
newVar('specpower','i')
newVar('specular','i')
newVar('specularExponent','i')
newVar('specularPercent','i')
newVar('specularPower','i')
newVar('spin','_spinX')
newVar('spinX','i')
newVar('spinY','i')
newVar('spinZ','i')
newVar('spinFps','i')
newVar('ssbond','_ssbonds')
newVar('ssbonds','BACKBONE,SIDECHAIN')
newVar('ssBondsBackbone','b')
newVar('statusReporting','b')
newVar('stereoDegrees','f')
newVar('strand','_strandCount')
newVar('strandCount','i')
newVar('strands','_strandCount')
newVar('testFlag1','reserved')
newVar('testFlag2','reserved')
newVar('testFlag3','reserved')
newVar('testFlag4','reserved')
newVar('toggleLabel','x')
newVar('traceAlpha','b')
newVar('unitcell','ijk,xyz')
newVar('vectorScale','f')
newVar('vibrationPeriod','f')
newVar('vibrationScale','f')
newVar('visualRange','f')
newVar('windowCentered','b')
newVar('zeroBasedXyzRasmol','b')
newVar('zoomEnabled','b')
newVar('zoomLarge','b')
newVar('zShade','b')
