desktop/jmol usr/bin

Jmol.jar usr/share/java

build/doc/JmolUserGuide/*.html usr/share/doc/jmol/html
build/doc/JmolUserGuide_fr/*.html usr/share/doc/jmol/html/fr

desktop/jmol.keys usr/share/mime-info
desktop/jmol.mime usr/share/mime-info

desktop/jmol.desktop usr/share/applications
desktop/jmol.desktop usr/share/applnk/Edutainment/Science
desktop/jmol.applications usr/share/application-registry
desktop/x-jmol.desktop usr/share/mimelnk/application

debian/jmol_icon.xpm usr/share/pixmaps
