#!/bin/sh
#
# Set JMOL_HOME and JAVA_HOME to match the appropriate installation 
# directories on your system:
#
# This executabe is adapted from the 'original' jmol for the Debian package
# by Egon Willighagen (egonw@sci.kun.nl)
#
JAVALIBS=/usr/share/java
EXTRALIBS=/usr/share/jmol/lib
JAVA_HOME=/usr/lib/jdk1.1
#
# This classpath line should be OK for JDK 1.1.  Comment it out if you have 1.2
#
CLASSPATH=${JAVALIBS}/jmol.jar:$JAVA_HOME/lib/classes.zip:$JAVA_HOME/lib/rt.jar:${EXTRALIBS}/swing.jar:${EXTRALIBS}/multi.jar:${JAVALIBS}/repository:${EXTRALIBS}/gnujaxp.jar:${EXTRALIBS}/cdk-cml.jar:${EXTRALIBS}/Acme.jar:${EXTRALIBS}/vecmath1.1-1.12.jar:${EXTRALIBS}/jas.jar:${EXTRALIBS}/itext-0.94.jar
export CLASSPATH

if test -n "$JAVA_HOME"; then
  export JAVA_HOME
  PATH=${JAVA_HOME}/bin:${PATH}
  export PATH
fi

/usr/bin/java -classpath ${CLASSPATH} -Djmol.home=~ org.openscience.jmol.Jmol
