.TH NAME SECTION
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
jmol \- programs to do something
.SH SYNOPSIS
.B jmol
.br
.SH "DESCRIPTION"
This manual page documents briefly the
.BR jmol 
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
Instead, it has documentation in the GNU Info format; see below.
.PP
.B jmol
is a program that is able to view 3D chemical information like molecular
structures, vibrations of bonds or animations. 
.SH SEE ALSO
More information about Jmol can be found at http://www.openscience.org/jmol/.
.SH AUTHOR
This manual page was written by Egon Willighagen <egonw@sci.kun.nl>,
for the Debian GNU/Linux system (but may be used by others).
